wing:
  AR_scale: [0.8, 1.2]
  taper: [0.40, 0.80]
  dihedral_deg: [3.0, 12.0]
  twist_root_deg: [0.0, 5.0]
  twist_tip_deg: [-5.0, 0.0]

tail:
  span_frac: [0.22, 0.42]
  AR: [2.6, 6.0]
  boom_len_m: [0.28, 0.60]
  incidence_deg: [-8.0, 8.0]

controls:
  de_cr_deg: [-15.0, 15.0]
  de_cl_deg: [-20.0, 20.0]
  a_cr_deg:  [-2.0, 16.0]
  a_cl_deg:  [0.0, 18.0]

fuselage:
  Lf_m: [0.40, 0.80]
  df_m: [0.05, 0.14]
